### ISSUE TITLE
Datatype of entries in discretes

### ISSUE THREAD

**Issue by teonlamont** [pyeparse/pyeparse#52]
what are the data types of the fixations and saccades in discretes? I checked and it returns numpy.void, but I don't know what this is. It seems to function as both a structured array and a ndarray. I am trying to add a dimension to it but I can't concatenate, hstack, or vstack.

**Comment by dengemann** [comment]
eI think it's a list of record arrays. You cannot concatneate them this way.
take a look at numpy.lib.recfunctions:

http://stackoverflow.com/questions/12090345/numpy-concatenate-on-record-arrays-fails-when-array-has-different-length-strings
